language: android
jdk: oraclejdk8
android:
components:
# use the latest revision of Android SDK Tools
- tools
- build-tools-25.0.2
- extra-google-m2repository
- extra-android-m2repository
- platform-tools

# The BuildTools version used by your project

# The SDK version used to compile your project
- android-17

- sys-img-armeabi-v7a-android-17
script: cd fireeasyjavaandroid && ./gradlew test

#licenses:
#- 'android-sdk-preview-license-.+'
#- 'android-sdk-license-.+'
# Additional components
