language: android
sudo: false
android:
  components:
    - tools
    - build-tools-25.0.2
    - platform-tools
    - extra-android-m2repository
    - extra-google-android-support
    # The BuildTools version used by your project
    #- build-tools-19.1.0

    # The SDK version used to compile your project
    - android-17
    - android-25

    # Additional components

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-17
    - sys-img-armeabi-v7a-android-25
jdk: oraclejdk8
os:
  - linux
script: cd fireeasyjavaandroid && ./gradlew test
before_install:
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
# language: android
# jdk: oraclejdk8
# android:
# components:
# # use the latest revision of Android SDK Tools
# - tools
# - build-tools-25.0.2
# - extra-google-m2repository
# - extra-android-m2repository
# - platform-tools
# 
# # The BuildTools version used by your project
# 
# # The SDK version used to compile your project
# - android-17
# 
# - sys-img-armeabi-v7a-android-17
# script: cd fireeasyjavaandroid && ./gradlew test
# 
# #licenses:
# #- 'android-sdk-preview-license-.+'
# #- 'android-sdk-license-.+'
# # Additional components
